version: '3.8'

services:
  postgres:
    container_name: pg_payment_prod
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512m

  redis:
    container_name: redis_payment_prod
    restart: always
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 256m

  kafka:
    container_name: kafka_payment_prod
    restart: always
    volumes:
      - kafka_data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          memory: 512m

volumes:
  pg_data:
  redis_data:
  kafka_data: